---
title: "Proceso de instalación"
author: "jeol"
date: "2022-08-15"
output: html_document
---

## Instalación de R y R-Studio

A continuación se presenta un resumen de como instalar R y RStudio.

# Instalación de R

La manera de instalar R cambia dependiendo del sistema operativo utilices pero todas tienen en común el uso de CRAN.

CRAN es el The Comprehensive R Archive Network, una red en la que se archivan todas las versiones de R base, así como todos los paquetes para R que han pasado por un proceso de revisión riguroso, realizado por el CRAN Team, que se encarga de asegurar su correcto funcionamiento.

CRAN es una red porque existen copias de su contenido en diferentes servidores alrededor del mundo, los cuales se actualizan diariamente. De este modo, no importa de qué servidor de CRAN descargues R o algún paquete, lo que vas a obtener será la versión más reciente de ese recurso, que es igual a la disponible en todos los demás servidores.

Como se abordará más adelante, cuando  se descarga un paquete de R, se está haciendo desde CRAN, a menos que indiquemos otra cosa.

El sitio oficial de CRAN, en el que encontrarás más información sobre este repositorio es el siguiente:

- https://cran.r-project.org/
- https://cran.r-project.org/bin/windows/base/ (para windows)
- https://cran.r-project.org/bin/macosx/ (para mac)
- https://cran.r-project.org/bin/linux/ (para linux)

# R-Studio

Para instalar RStudio, es necesario con descargar y ejecutar alguno de los instaladores disponibles en su sitio oficial. Están disponibles versiones para Windows, OSX y Linux.

- https://www.rstudio.com/products/rstudio/download/

Se debe instalar preliminarmente R en el equipo, para que RStudio lo detecte  automáticamente y poderlo utilizarlo desde este entorno. 

Para complementar las instlación y Si se tiene problemas con la generación del PDF usando un Rmd, pruebe ejecutar antes la actualización de MarkDown a la versión compatible con las librerías de R:

- install.packages("devtools")
- library(devtools)
- install_version("rmarkdown", version = 1.8)

También es recomendable instalar tinytex 
- install.packages("tinytex")
- tinytex::install_tinytex()

# Colab
Aunque Colab se usa principalmente para codificar en Python, también se puede usar para R ( #Rstats ). Hay dos formas de ejecutar R en Colab
- La primera forma es usar el paquete rpy2 en el tiempo de ejecución de Python. Este método le permite ejecutar la sintaxis de R y Python juntas.
- La segunda forma es iniciar el cuaderno en el tiempo de ejecución de R con:
- *https://colab.to/r*

# Paquetes

Son librerías con funciones y datos que no necesariamente vienen instaladas por defecto.

Para instalar un paquete existen varias formas, un a de ellas es a través de las sentencias:

- install.package("nombre_paquete", dep = TRUE), esto instala o actualiza un paquete, (dep de dependencias)
- library(nombre_paquete), permite cargar un paquete ya instalado

Ejemplo:

- install.package("tidyverse", dep = TRUE)
- library(tidyverse)
- Sitio documentación del paquete, https://www.tidyverse.org/

# Referencias

- Institute for Statistics and Mathematics of WU (Wirtschaftsuniversität Wien). The Comprehensive R Archive Network. Recuperado en agosto de 2022 de: https://cran.r-project.org/
- Adityawarman Fidocia Wilma. Cómo usar R en Google Colab. Recuperado en agosto de 2022 de: https://towardsdatascience.com/how-to-use-r-in-google-colab-b6e02d736497


